#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### COLOR PALETTE (Catppuccin Mocha) #####
BASE=0xff1e1e2e
SURFACE=0xff313244
TEXT=0xffcdd6f4
SUBTEXT=0xffa6adc8

BLUE=0xff89b4fa
GREEN=0xffa6e3a1
YELLOW=0xfff9e2af
RED=0xfff38ba8
MAUVE=0xffcba6f7

##### BAR APPEARANCE #####
sketchybar --bar \
  position=top \
  height=40 \
  blur_radius=30 \
  color=$BASE

##### DEFAULT ITEM STYLE #####
default=(
  padding_left=6
  padding_right=6
  icon.font="JetbrainsMono Nerd Font:Bold:14.0"
  label.font="JetbrainsMono Nerd Font:Bold:14.0"
  icon.color=$TEXT
  label.color=$TEXT
  background.color=$SURFACE
  background.corner_radius=6
  background.height=26
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=6
  label.padding_right=6
)
sketchybar --default "${default[@]}"

##### SPACE GROUP BACKGROUND #####
sketchybar --add bracket spaces left \
           --set spaces \
             background.color=$SURFACE \
             background.corner_radius=8 \
             background.height=26 \
             padding_left=3 \
             padding_right=3




##### SPACES (YABAI) #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"; do
  sid="$(($i+1))"
  sketchybar --add space space.$sid left \
             --set space.$sid \
               space=$sid \
               icon="${SPACE_ICONS[i]}" \
               icon.color=$SUBTEXT \
               label.drawing=off \
               background.drawing=off \
               padding_left=3 \
               padding_right=3ß \
               script="$PLUGIN_DIR/space.sh" \
               click_script="yabai -m space --focus $sid" \
               bracket=spaces
done




##### LEFT ITEMS #####
sketchybar --add item chevron left \
           --set chevron \
             icon= \
             icon.color=$MAUVE \
             label.drawing=off \
             background.color=0x00000000

sketchybar --add item front_app left \
           --set front_app \
             icon.drawing=off \
             label.color=$BLUE \
             background.color=$SURFACE \
             script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### RIGHT ITEMS #####

# Clock
sketchybar --add item clock right \
           --set clock \
             update_freq=10 \
             icon= \
             icon.color=$YELLOW \
             label.color=$TEXT \
             background.color=$SURFACE \
             script="$PLUGIN_DIR/clock.sh"

# Volume
sketchybar --add item volume right \
           --set volume \
             icon.color=$BLUE \
             label.color=$TEXT \
             background.color=$SURFACE \
             script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change

# Battery
sketchybar --add item battery right \
           --set battery \
             icon.color=$GREEN \
             label.color=$TEXT \
             background.color=$SURFACE \
             update_freq=120 \
             script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change


##### FORCE INITIAL UPDATE #####
sketchybar --update
